FROM registry.devshift.net/fabric8-analytics/f8a-npm-insights:latest

LABEL MAINTAINER="Avishkar Gupta <avgupta@redhat.com>"

# --------------------------------------------------------------------------------------------------
# copy testing source code and scripts into root dir /
# --------------------------------------------------------------------------------------------------
ADD ./tests/ /tests
ADD ./tests/scripts/entrypoint-test.sh /entrypoint-test.sh
RUN chmod 0777 /entrypoint-test.sh

ENV PYTHONPATH=/

RUN pip3 install pytest

# --------------------------------------------------------------------------------------------------
# RUN THE UNIT TESTS
# --------------------------------------------------------------------------------------------------
ENTRYPOINT ["/entrypoint-test.sh"]
