version: "3"
services:
  chester:
    build:
      context: .
      dockerfile: Dockerfile
    image: quay.io/openshiftio/fabric8-analytics-f8a-npm-insights:latest
    network_mode: bridge
    entrypoint:
      - /bin/entrypoint.sh
    environment:
      AWS_S3_ACCESS_KEY_ID: "${AWS_S3_ACCESS_KEY_ID}"
      AWS_S3_SECRET_ACCESS_KEY: "${AWS_S3_SECRET_ACCESS_KEY}"
      # Minio for AWS simulation in local deployment
      AWS_S3_ENDPOINT_URL: "${AWS_S3_ENDPOINT_URL}"
      CHESTER_SCORING_REGION: "npm"
      # Accepted values - dev | stage | prod
      DEPLOYMENT_PREFIX: "dev"
      SERVICE_PORT: "6006"
      SERVICE_TIMEOUT: "900"
      S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
      # Assume that minio will be used.
      USE_CLOUD_SERVICES: "True"
      PYTHONUNBUFFERED: 0
      MIN_REC_CONFIDENCE: 30
    ports:
      - "6006:6006"
