PMF_MODEL_PATH = 'model-cf10/pmf-packagedata.mat'
PACKAGE_TO_ID_MAP = 'node-pmf-scoring/package_to_index_map.json'
ID_TO_PACKAGE_MAP = 'node-pmf-scoring/index_to_package_map.json'
PRECOMPUTED_STACKS = 'training-data-node/manifest_user_data.dat'
TRAINING_DATA_ITEMS = 'training-data-node/packagedata-train-5-items.dat'
PACKAGE_TAG_MAP = 'node-pmf-scoring/package_tag_map.json'
