apiVersion: v1
kind: Template
labels:
  template: f8a-npm-insights
metadata:
  name: f8a-npm-insights
  annotations:
    description: f8a-npm-insights
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: f8a-npm-insights
    name: f8a-npm-insights
  spec:
    replicas: "${{REPLICAS}}"
    selector:
      service: f8a-npm-insights
    template:
      metadata:
        labels:
          service: f8a-npm-insights
      spec:
        containers:
        - command:
          - /bin/entrypoint.sh
          env:
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: SERVICE_PORT
            value: "6006"
          - name: SERVICE_TIMEOUT
            value: "900"
          - name: CHESTER_SCORING_REGION
            value: "${CHESTER_SCORING_REGION}"
          - name: AWS_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: aws_access_key_id
                name: cvae-npm-insights-s3
          - name: AWS_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: aws_access_key_id
                name: cvae-npm-insights-s3
          - name: FLASK_LOGGING_LEVEL
            value: ${FLASK_LOGGING_LEVEL}
          - name: AWS_S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                key: bucket
                name: cvae-npm-insights-s3
          - name: MODEL_VERSION
            value: ${MODEL_VERSION}
          - name: MIN_REC_CONFIDENCE
            value: ${MIN_REC_CONFIDENCE}
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: worker
                key: sentry_dsn

          name: f8a-npm-insights
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          ports:
          - containerPort: 6006
          livenessProbe:
            httpGet:
              path: /api/v1/liveness
              port: 6006
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/readiness
              port: 6006
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 30
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: f8a-npm-insights
    name: f8a-npm-insights
  spec:
    ports:
    - port: 6006
      targetPort: 0
    selector:
      service: f8a-npm-insights

parameters:
- description: CPU request
  displayName: CPU request
  required: true
  name: CPU_REQUEST
  value: "300m"

- description: CPU limit
  displayName: CPU limit
  required: true
  name: CPU_LIMIT
  value: "300m"

- description: Memory request
  displayName: Memory request
  required: true
  name: MEMORY_REQUEST
  value: "1Gi"

- description: Memory limit
  displayName: Memory limit
  required: true
  name: MEMORY_LIMIT
  value: "1Gi"

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "quay.io"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "openshiftio/rhel-fabric8-analytics-f8a-npm-insights"

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Chester Scoring Region - npm
  displayName: Chester Scoring Region
  required: true
  name: CHESTER_SCORING_REGION
  value: "npm"

- description: "Flask logging level (see: https://docs.python.org/3/library/logging.html#levels)"
  displayName: Flask logging level
  required: false
  name: FLASK_LOGGING_LEVEL
  value: "WARNING"

- description: "Model Version - Date Format YYYY-MM-DD"
  displayName: Model Version
  required: true
  name: MODEL_VERSION
  value: "2019-01-03"

- description: "Minimum recommendation confidence probability"
  displayName: Minimum recommendation confidence
  required: true
  name: MIN_REC_CONFIDENCE
  value: "30"
